### login user test0@ for ROLE_ADMIN, test1 to n@ for ROLE_USER
POST localhost:3001/api/v1/auth/login
Content-Type: application/json

{
  "email": "test0@test.com",
  "password": "1234"
}

### login user test0@ to receive iot-sensor token
POST localhost:3001/api/v1/auth/login-iot
Content-Type: application/json

{
  "email": "test0@test.com",
  "password": "1234"
}

### get SELF user ROLE_ADMIN by id
GET localhost:3001/api/v1/users/{{idAdmin}}
Content-Type: application/json
Authorization: Bearer: {{jwtAdmin}}

### get OTHER user ROLE_ADMIN by id - should 200
GET localhost:3001/api/v1/users/{{idUser1}}
Content-Type: application/json
Authorization: Bearer: {{jwtAdmin}}

### get SELF user ROLE_USER by id - should 200
GET localhost:3001/api/v1/users/{{idUser1}}
Content-Type: application/json
Authorization: Bearer: {{jwtUser1}}

### get OTHER user ROLE_USER by id - should 401
GET localhost:3001/api/v1/users/{{idUser2}}
Content-Type: application/json
Authorization: Bearer: {{jwtUser1}}

### get animal kind - should work for all users
GET localhost:3001/api/v1/animalKinds/65379d97ba30a98c1dcc8063
Accept: application/json
Authorization: Bearer: {{jwtUser1}}

### get animal kind - should 404
GET localhost:3001/api/v1/animalKinds/653f8e11496a4335957d81d0
Accept: application/json
Authorization: Bearer: {{jwtUser1}}

### get all animal kinds - should 200
GET localhost:3001/api/v1/animalKinds
Accept: application/json
Authorization: Bearer: {{jwtUser1}}

### send data to iot endpoint
POST localhost:3001/api/v1/terrariumData
Content-Type: application/json
Authorization: Bearer: {{iotSensorJwtAdmin}}

{
  "value": 29.5,
  "sensorId": "12aef2bd83b3",
  "topic": "temperature"
}

### get ALL USERS by user ROLE_ADMIN
GET localhost:3001/api/v1/users/
Content-Type: application/json
Authorization: Bearer: {{jwtAdmin}}

### get ALL USERS by user ROLE_ADMIN
GET localhost:3001/fe/v1/users?fields=terrariums
Content-Type: application/json
Authorization: Bearer: {{jwtAdmin}}

### get ALL TERRARIUMS of a userId
GET localhost:3001/fe/v1/users/{{idAdmin}}/terrariums
Content-Type: application/json
Authorization: Bearer: {{jwtAdmin}}

### get DATA by hardwarioCode and userId
GET localhost:3001/fe/v1/users/{{idAdmin}}/terrariumsHc/12aef2bd83b3
Content-Type: application/json
Authorization: Bearer: {{jwtAdmin}}

### get TERRARIUM by id and userId
GET localhost:3001/fe/v1/users/{{idAdmin}}/terrariumsId/6553ed4aeb48fff32c22ea9a
Content-Type: application/json
Authorization: Bearer: {{jwtAdmin}}

### get DATA of a terrariumId and userId
GET localhost:3001/fe/v1/users/{{idAdmin}}/terrariumsId/6553ed4aeb48fff32c22ea9a/data
Content-Type: application/json
Authorization: Bearer: {{jwtAdmin}}

### get DATA of a terrariumId and userId
POST localhost:3001/fe/v1/users/{{idAdmin}}/terrariums
Content-Type: application/json
Authorization: Bearer: {{jwtAdmin}}

{
  "name": "test1",
  "animalType": "type1",
  "description": "description",
  "targetLivingConditions": {
    "humidity": {
      "min": 1,
      "max": 1
    },
    "temperature": {
      "min": 1,
      "max": 1
    },
    "lightIntensity": {
      "min": 1,
      "max": 1
    }
  },
  "hardwarioCode": "hardwarioCode1",
  "data": []
}

### delete terrarium of a user
DELETE localhost:3001/fe/v1/users/{{idAdmin}}/terrariums/656243a88bb6c9d9a6dcb82a
Content-Type: application/json
Authorization: Bearer: {{jwtAdmin}}
