### login user test0@ for ROLE_ADMIN, test1 to n@ for ROLE_USER
POST localhost:3001/api/v1/auth/login
Content-Type: application/json

{
  "email": "test0@test.com",
  "password": "1234"
}

### login user test0@ for ROLE_ADMIN, test1 to n@ for ROLE_USER
POST localhost:3001/api/v1/auth/login
Content-Type: application/json

{
  "email": "test0@test.com",
  "password": "1234"
}

### GET IOT TOKEN
GET localhost:3001/api/v1/auth/iot-token
Content-Type: application/json
Authorization: Bearer: {{jwtAdmin}}

### get SELF user ROLE_ADMIN by id
GET localhost:3001/api/v1/users/{{idAdmin}}
Content-Type: application/json
Authorization: Bearer: {{jwtAdmin}}

### get SELF user ROLE_ADMIN by id
GET https://jittery-ruby-pigeon.cyclic.app/api/v1/users/{{idAdmin}}
Content-Type: application/json
Authorization: Bearer: {{jwtAdmin}}

### POST USER
POST localhost:3001/api/v1/users
Content-Type: application/json

{
  "firstName": "Petra",
  "lastName": "Novotna",
  "email": "petra@test.com",
  "roles": [
    "ROLE_USER"
  ],
  "password": "1234"
}

### get OTHER user ROLE_ADMIN by id - should 200
GET localhost:3001/api/v1/users/{{idUser1}}
Content-Type: application/json
Authorization: Bearer: {{jwtAdmin}}

### get SELF user ROLE_USER by id - should 200
GET localhost:3001/api/v1/users/{{idUser1}}
Content-Type: application/json
Authorization: Bearer: {{jwtUser1}}

### get OTHER user ROLE_USER by id - should 401
GET localhost:3001/api/v1/users/{{idUser2}}
Content-Type: application/json
Authorization: Bearer: {{jwtUser1}}

### get animal kind - should work for all users
GET localhost:3001/api/v1/animalKinds/65379d97ba30a98c1dcc8063
Accept: application/json
Authorization: Bearer: {{jwtUser1}}

### get animal kind - should 404
GET localhost:3001/api/v1/animalKinds/653f8e11496a4335957d81d0
Accept: application/json
Authorization: Bearer: {{jwtUser1}}

### get all animal kinds - should 200
GET{{deploymentUrl}}/api/v1/animalKinds
Accept: application/json
Authorization: Bearer: {{jwtUser1}}

### send data to iot endpoint
POST localhost:3001/api/v1/terrariumData
Content-Type: application/json
Authorization: Bearer: {{iotSensorJwtAdmin}}

{
  "value": 29.5,
  "sensorId": "12aef2bd83b3",
  "topic": "xys/syx/temperature"
}

### get ALL USERS by user ROLE_ADMIN
GET localhost:3001/api/v1/users/
Content-Type: application/json
Authorization: Bearer: {{jwtAdmin}}

### get ALL TERRARIUMS of a userId
GET localhost:3001/fe/v1/users/{{idAdmin}}/terrariums
Content-Type: application/json
Authorization: Bearer: {{jwtAdmin}}

### get USER ID populated with all terrariums
GET localhost:3001/fe/v1/users/{{idAdmin}}/populated
Content-Type: application/json
Authorization: Bearer: {{jwtAdmin}}

### get DATA by hardwarioCode and userId
GET localhost:3001/fe/v1/users/{{idAdmin}}/terrariumsHc/12aef2bd83b3
Content-Type: application/json
Authorization: Bearer: {{jwtAdmin}}

### get TERRARIUM by id and userId
GET localhost:3001/fe/v1/users/{{idAdmin}}/terrariums/658ee1984417a895b83d2fee
Content-Type: application/json
Authorization: Bearer: {{jwtAdmin}}

### get DATA of a terrariumId and userId
GET localhost:3001/fe/v1/users/{{idAdmin}}/terrariums/658ee1984417a895b83d2fee/data
Content-Type: application/json
Authorization: Bearer: {{jwtAdmin}}

### POST terrarium to user
POST localhost:3001/fe/v1/users/{{idAdmin}}/terrariums
Content-Type: application/json
Authorization: Bearer: {{jwtAdmin}}

{
  "name": "Pavouk Anezka4",
  "animalType": "Tarantule",
  "description": "Anezka je mily a nenarocny pavouk. Krmime drobnym hmyzem jednou za 14 dni.",
  "targetLivingConditions": {
    "humidity": {
      "min": 50,
      "max": 90
    },
    "temperature": {
      "min": 30,
      "max": 35
    },
    "lightIntensity": {
      "min": 0,
      "max": 100
    }
  },
  "hardwarioCode": "mock-code4",
  "data": []
}

### delete terrarium of a user - deletes the terrarium from all users
DELETE localhost:3001/fe/v1/users/{{idAdmin}}/terrariums/65abca1191800f208c12ce6c
Content-Type: application/json
Authorization: Bearer: {{jwtAdmin}}

### addTerrariumIdToAnotherUserId - ads existing terrarium to selected user
PATCH localhost:3001/fe/v1/users/{{idAdmin}}/terrariums/65abb7eab1b808a504400584
Content-Type: application/json
Authorization: Bearer: {{jwtAdmin}}

### edit terrarium of a user
PUT localhost:3001/fe/v1/users/{{idAdmin}}/terrariums/65abc9dd2047b0a58aa04892
Content-Type: application/json
Authorization: Bearer: {{jwtAdmin}}

{
  "targetLivingConditions": {
    "humidity": {
      "min": 1,
      "max": 1
    },
    "temperature": {
      "min": 1,
      "max": 1
    },
    "lightIntensity": {
      "min": 1,
      "max": 1
    }
  },
  "name": "BLEBLEBLEBLEBLEBLE",
  "animalType": "type11",
  "description": "description1",
  "hardwarioCode": "mock-code2",
  "data": []
}

### edit terrarium of a user - not existing terrariumId
PUT localhost:3001/fe/v1/users/{{idAdmin}}/terrariums/656f91bdc6a5232e7d289d75
Content-Type: application/json
Authorization: Bearer: {{jwtAdmin}}

{
  "name": "ahoj",
  "animalType": "asdasd",
  "description": "asdasd",
  "targetLivingConditions": {
    "humidity": {
      "min": 0,
      "max": 0
    },
    "temperature": {
      "min": 10,
      "max": 100
    },
    "lightIntensity": {
      "min": 0,
      "max": 0
    }
  },
  "hardwarioCode": "555555",
  "data": null,
  "_id": "65636d64c86ecee49fe6309a"
}